services:
  cadvisor:
    restart: unless-stopped
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    expose:
      - 8080
    ports:
      - "8005:8080"
    networks:
      - monitoring
#    command: --disable_metrics=diskIO

  sonos-web:
    image: sonosweb/sonos-web:1.0.0
    restart: unless-stopped
    network_mode: host

  rsync-obd:
    image: axiom/rsync-server:latest
    restart: unless-stopped
    volumes:
      - ./obd:/data
    ports:
      - 8730:873
    environment:
      - USERNAME=obd
      - PASSWORD=obd


networks:
  monitoring:
    driver: bridge
