services:
  cadvisor:
    restart: unless-stopped
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    expose:
      - 8080
    ports:
      - "8005:8080"
    networks:
      - monitoring
#    command: --disable_metrics=diskIO

  rsync-obd:
    image: axiom/rsync-server:latest
    restart: unless-stopped
    volumes:
      - ./obd:/data
    ports:
      - 8730:873
    environment:
      - USERNAME=obd
      - PASSWORD=obd

  unifi-controller:
    image: linuxserver/unifi-controller:LTS
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped


networks:
  monitoring:
    driver: bridge
