services:
  traefik:
    container_name: traefik
    image: traefik:saintmarcelin
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.web.address=:80"
      - "--certificatesResolvers.le.acme.email=trick@vanstaveren.us"
      - "--certificatesResolvers.le.acme.storage=/acme/acme.json"
      #- "--certificatesResolvers.le.acme.storage=/acme/acme-staging.json"
      #- "--certificatesResolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.le.acme.tlsChallenge=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--metrics.prometheus=true"
      - "--entryPoints.metrics.address=:7082"
      #- "--accesslog=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/acme/:/acme/"
    labels:
      - com.centurylinklabs.watchtower.enable=true
    network_mode: host
    mem_limit: 100m
  
  tcpproxy_traefik_metrics:
    container_name: tcpproxy_traefik_metrics
    image: amaysim/docker-tcp-proxy
    restart: unless-stopped
    environment:
      - CONTAINER_PORT=80
      - REMOTE_HOST=172.17.0.1
      - REMOTE_PORT=7082
    mem_limit: 10m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefikmetrics.rule=Host(`traefikmetrics.home.v9n.us`, `tm22.home.v9n.us`)"
      - "traefik.http.routers.traefikmetrics.entrypoints=websecure"
      - "traefik.http.routers.traefikmetrics.tls.certresolver=le"
      - "traefik.http.services.traefikmetrics.loadbalancer.server.port=80"
      - "traefik.http.routers.traefikmetrics.middlewares=traefikmetricsauth"
      # Note: when used in docker-compose.yml all dollar signs in the hash need to be doubled for escaping.
      # To create user:password pair, it's possible to use this command:
      # echo $(htpasswd -nB user) | sed -e s/\\$/\\$\\$/g
      - "traefik.http.middlewares.traefikmetricsauth.basicauth.users=foo:$$2y$$05$$/GTEnG5nDTMb2wAyPiioFeR1igHfvU31f9xRLCOvS0VBDYzY16BPe" # this is in /etc/prometheus/prometheus.yml on hg.v9n.us

  whoami44:
    image: containous/whoami
    restart: unless-stopped
    mem_limit: 20m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami44.entrypoints=websecure"
      - "traefik.http.routers.whoami44.tls.certresolver=le"
      - "traefik.http.routers.whoami44.rule=Host(`whoami44.home.v9n.us`, `whoami78.home.v9n.us`)"
      - "traefik.http.services.whoami44.loadbalancer.server.port=80"

  cadvisor:
    restart: unless-stopped
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    expose:
      - 8080
    ports:
      - "8005:8080"
    networks:
      - monitoring
#    command: --disable_metrics=diskIO
    mem_limit: 200m

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_LABEL_ENABLE: 1          # Only include containers with enable label
    #command: -i 10
    mem_limit: 75m

  rsync-obd:
    image: axiom/rsync-server:latest
    restart: unless-stopped
    volumes:
      - ./obd:/data
    ports:
      - 8730:873
    environment:
      - USERNAME=obd
      - PASSWORD=obd
    mem_limit: 15m

  unifi-controller:
    image: linuxserver/unifi-controller:LTS
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1400M
      - MEM_STARTUP=1400M
#    mem_limit: 1500m
    volumes:
      - ./unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8060:8060
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped
  
  hass:
    container_name: hass
    image: homeassistant/home-assistant:stable
    volumes:
      - ./hass-config:/config
    devices:
      - /dev/ttyUSB0
    environment:
      - TZ=America/Chicago
    restart: always
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hass.rule=Host(`hass.vanstaveren.us`)"
      - "traefik.http.routers.hass.entrypoints=websecure"
      - "traefik.http.routers.hass.tls.certresolver=le"
      - "traefik.http.services.hass.loadbalancer.server.port=8123"
      - com.centurylinklabs.watchtower.enable=true
  
  esphome:
    image: esphome/esphome:stable
    container_name: esphome
    restart: unless-stopped
    volumes:
      - /home/trick/src/github.com/trickv/my-esphome:/config
    mem_limit: 500m
    network_mode: host
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "traefik.enable=true"
      - "traefik.http.routers.esphome.rule=Host(`esphome.home.v9n.us`)"
      - "traefik.http.routers.esphome.entrypoints=websecure"
      - "traefik.http.routers.esphome.tls.certresolver=le"
      - "traefik.http.routers.esphome.middlewares=github-auth"
      - "traefik.http.services.esphome.loadbalancer.server.port=6052"


  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./matter:/data
      - /run/dbus:/run/dbus:ro
    mem_limit: 300m
    security_opt:
      - apparmor=unconfined
    labels:
      - com.centurylinklabs.watchtower.enable=true
    

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./mqtt:/mosquitto
    mem_limit: 50m
    labels:
      - com.centurylinklabs.watchtower.enable=true

  airsonic:
    container_name: airsonic
    image: linuxserver/airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      #- CONTEXT_PATH=<URL_BASE> #optional
      #- JAVA_OPTS=<options> #optional
    volumes:
      - ./airsonic-config:/config
      - /mnt/music/Master_Collection:/music
    mem_limit: 1000m
    ports:
      - 4039:4040
      - 8444:8443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airsonic.rule=Host(`airsonic.home.v9n.us`)"
      - "traefik.http.routers.airsonic.entrypoints=websecure"
      - "traefik.http.routers.airsonic.tls.certresolver=le"
      - "traefik.http.services.airsonic.loadbalancer.server.port=4040"

  nextcloud:
    container_name: nextcloud
    image: nextcloud:production-apache
    volumes:
      - /mnt/nextcloud:/var/www/html
      - /mnt/pictures:/mnt/pictures
      - /mnt/music/Master_Collection:/mnt/music
    mem_limit: 1500m
    restart: unless-stopped
    environment:
      - NEXTCLOUD_TRUSTED_DOMAIN=nextcloud.home.v9n.us"
      - TRUSTED_PROXIES=172.16.0.0/12
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.home.v9n.us`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=le"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

  snmp_exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    restart: unless-stopped
    ports:
      - 9116:9116
    mem_limit: 50m
    labels:
      - com.centurylinklabs.watchtower.enable=true

  solaredge_exporter:
    image: dave92082/solaredge-exporter:1.1
    container_name: solaredge-exporter
    restart: unless-stopped
    ports:
      - 2112:2112
    mem_limit: 50m
    environment:
      - INVERTER_ADDRESS=solaredge-inverter.home.vanstaveren.us
      - EXPORTER_INTERVAL=5
      - INVERTER_PORT=1502

  bb_exporter:
    image: prom/blackbox-exporter:latest
    container_name: bb
    restart: unless-stopped
    volumes:
      - ./monitoring/bb:/config
    ports:
      - 9115:9115
    mem_limit: 30m
    labels:
      - com.centurylinklabs.watchtower.enable=true
    command: --config.file=/config/blackbox.yml

# docker run -d --restart unless-stopped --name sb8200-exporter -p 9195:9195 sbrudenell/sb8200_exporter
  sb8200_exporter:
    image: sbrudenell/sb8200_exporter
    container_name: sb8200_exporter
    restart: unless-stopped
    ports:
      - 9195:9195
    mem_limit: 60m
  
  unifi-poller:
    container_name: unifi-poller
    image: golift/unifi-poller
    volumes:
      - ./monitoring/unifi-poller/unifi-poller.conf:/config/unifi-poller.conf
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - 9130:9130
    mem_limit: 20m

  prometheus:
    image: prom/prometheus:latest
    container_name: prom
    restart: unless-stopped
    volumes:
      - ./monitoring/prom/master:/prometheus
      - ./monitoring/prom/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    labels:
      - com.centurylinklabs.watchtower.enable=true
    mem_limit: 700m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.home.v9n.us`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls.certresolver=le"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.middlewares=prometheusauthmiddleware"
      # to create a password: echo $(htpasswd -nB user) | sed -e s/\\$/\\$\\$/g
      - "traefik.http.middlewares.prometheusauthmiddleware.basicauth.users=prometheus:$$apr1$$u13f5Obh$$ERJ3TfhQ/Wsz3gpwGj9gd1,hgscripts:$$apr1$$lMM3tlNn$$jaJu0WEaL2JzeTpgAkfs40"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=30d
      - --web.enable-admin-api
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
  
  grafana:
    image: grafana/grafana:9.0.2
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    mem_limit: 250m
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.home.v9n.us`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=le"
      - "traefik.http.routers.grafana.middlewares=github-auth"
    environment:
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel,flant-statusmap-panel"
      - "GF_AUTH_PROXY_ENABLED=true"
      - "GF_AUTH_PROXY_HEADER_NAME=X-Firwarded-User"
      - "GF_USERS_ALLOW_SIGN_UP=false"
      - "GF_USERS_AUTO_ASSIGN_ORG=true"
      - "GF_USERS_AUTO_ASSIGN_ORG_ROLE=Editor"
      - "GF_FOO_BAR=Editor"

  github-auth:
    container_name: github-auth
    image: thomseddon/traefik-forward-auth:latest # must run latest for auth mode because https://github.com/thomseddon/traefik-forward-auth/pull/217
    restart: unless-stopped
    mem_limit: 20m
    environment:
      - DEFAULT_PROVIDER=generic-oauth
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=https://github.com/login/oauth/authorize
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=https://github.com/login/oauth/access_token
      - PROVIDERS_GENERIC_OAUTH_USER_URL=https://api.github.com/user
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID=4126728948d59d9ffe20
      - COOKIE_DOMAIN=home.v9n.us
      - AUTH_HOST=auth.home.v9n.us
      - LOG_LEVEL=trace
      - LOG_FORMAT=json
      - DOMAIN=vanstaveren.us
      - COOKIE_NAME=_fw_gh_auth2
      - CSRF_COOKIE_NAME=_fw_csrf_gh_auth2
    ports:
      - 4181:4181
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.github-auth.forwardauth.address=http://172.17.0.1:4181"
      - "traefik.http.middlewares.github-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.github-auth.loadbalancer.server.port=4181"
      - "traefik.http.routers.github-auth.entrypoints=websecure"
      - "traefik.http.routers.github-auth.tls.certresolver=le"
      - "traefik.http.routers.github-auth.rule=Host(`auth.home.v9n.us`)"

  whoami:
    image: containous/whoami
    restart: unless-stopped
    mem_limit: 10m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=le"
      - "traefik.http.routers.whoami.rule=Host(`whoami212.home.v9n.us`)"
      - "traefik.http.routers.whoami.middlewares=github-auth"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

  tftp_for_erlite_backup:
    image: jumanjiman/tftp-hpa
    restart: unless-stopped
    ports:
      - "69:69/udp"
    volumes:
      - ./erlite-backups:/backups
    entrypoint: ['in.tftpd', '-L', '-v', '-v', '-v', '--create', '--permissive', '-u', 'tftp', "-m", "/tftpboot/mapfile", '/backups']

  # https://community.home-assistant.io/t/openwakeword-docker/626131/5
  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    user: 1001:1001
    volumes:
      - ./wakeword/data:/data
      - ./wakeword/custom:/custom
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      --preload-model 'ok_nabu'
      --custom-model-dir /custom
      --debug
      #--trigger-level 1
# --threshold Wake word model threshold (0-1, default: 0.5); hass uses 0.5 as default too
# --trigger-level Number of activations before detection (default: 4); hass uses 1 as default?!
    restart: unless-stopped
    ports:
      - 10400:10400/tcp
    mem_limit: 100m
    labels:
      - com.centurylinklabs.watchtower.enable=true

  whisper:
    image: rhasspy/wyoming-whisper:latest
    container_name: whisper
    ports:
      - 10300:10300
    restart: unless-stopped
    volumes:
      - ./whisper-data:/data
    command: [ "--model", "tiny", "--language", "en" ]
# models are {{tiny,base,small,medium,large},-int8}
    mem_limit: 500m
    labels:
      - com.centurylinklabs.watchtower.enable=true

  piper:
    image: rhasspy/wyoming-piper:latest
    container_name: piper
    ports:
      - 10200:10200
    restart: unless-stopped
    volumes:
      - ./piper-data:/data
    command: [ "--voice", "en_US-lessac-medium" ]
    mem_limit: 250m
    labels:
      - com.centurylinklabs.watchtower.enable=true


  proxy_prometheus:
    container_name: tcpproxy_prometheus
    image: amaysim/docker-tcp-proxy
    restart: unless-stopped
    environment:
      - CONTAINER_PORT=80
      - REMOTE_HOST=172.16.17.23
      - REMOTE_PORT=9090
    mem_limit: 10m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheusproxy.rule=Host(`prometheus-utc.home.v9n.us`)"
      - "traefik.http.routers.prometheusproxy.entrypoints=websecure"
      - "traefik.http.routers.prometheusproxy.tls.certresolver=le"
      - "traefik.http.services.prometheusproxy.loadbalancer.server.port=80"
      - "traefik.http.routers.prometheusproxy.middlewares=prometheusproxyauthmiddleware"
      - "traefik.http.middlewares.prometheusproxyauthmiddleware.basicauth.users=prometheus:$$apr1$$u13f5Obh$$ERJ3TfhQ/Wsz3gpwGj9gd1"
  
  proxy_autorx_radiopi:
    container_name: autorx_radiopi
    image: amaysim/docker-tcp-proxy
    restart: unless-stopped
    environment:
      - CONTAINER_PORT=80
      - REMOTE_HOST=radiopi.home.vanstaveren.us
      - REMOTE_PORT=5000
    mem_limit: 10m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.autorx-radiopi.rule=Host(`autorxradiopi.home.v9n.us`)"
      - "traefik.http.routers.autorx-radiopi.entrypoints=websecure"
      - "traefik.http.routers.autorx-radiopi.tls.certresolver=le"
      - "traefik.http.routers.autorx-radiopi.middlewares=github-auth"
      - "traefik.http.services.autorx-radiopi.loadbalancer.server.port=80"

  proxy_daylapse1:
    image: amaysim/docker-tcp-proxy
    restart: unless-stopped
    environment:
      - CONTAINER_PORT=80
      - REMOTE_HOST=daylapse1.home.vanstaveren.us
      - REMOTE_PORT=8080
    mem_limit: 10m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.daylapse.rule=Host(`daylapse.home.v9n.us`)"
      - "traefik.http.routers.daylapse.entrypoints=websecure"
      - "traefik.http.routers.daylapse.tls.certresolver=le"
      - "traefik.http.services.daylapse.loadbalancer.server.port=80"

  proxy_traefik_dashboard:
    image: amaysim/docker-tcp-proxy
    restart: unless-stopped
    environment:
      - CONTAINER_PORT=80
      - REMOTE_HOST=172.17.0.1
      - REMOTE_PORT=8080
    mem_limit: 10m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.home.v9n.us`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=le"
      - "traefik.http.routers.traefik-dashboard.middlewares=github-auth"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=80"
  
  proxy_openwebrx:
    image: amaysim/docker-tcp-proxy
    restart: unless-stopped
    environment:
      - CONTAINER_PORT=80
      - REMOTE_HOST=172.16.17.57
      - REMOTE_PORT=8073
    mem_limit: 10m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebrx.rule=Host(`openwebrx.home.v9n.us`)"
      - "traefik.http.routers.openwebrx.entrypoints=websecure"
      - "traefik.http.routers.openwebrx.tls.certresolver=le"
      - "traefik.http.routers.openwebrx.middlewares=github-auth"
      - "traefik.http.services.openwebrx.loadbalancer.server.port=80"
  
  proxy_octoprint:
    image: amaysim/docker-tcp-proxy
    restart: unless-stopped
    environment:
      - CONTAINER_PORT=80
      - REMOTE_HOST=octopi.home.vanstaveren.us
      - REMOTE_PORT=80
    mem_limit: 10m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.octoprint.rule=Host(`octoprint.home.v9n.us`)"
      - "traefik.http.routers.octoprint.entrypoints=websecure"
      - "traefik.http.routers.octoprint.tls.certresolver=le"
      - "traefik.http.routers.octoprint.middlewares=github-auth"
      - "traefik.http.services.octoprint.loadbalancer.server.port=80"
  
  proxy_adsb1:
    image: amaysim/docker-tcp-proxy
    restart: unless-stopped
    environment:
      - CONTAINER_PORT=80
      - REMOTE_HOST=adsb1.home.vanstaveren.us
      - REMOTE_PORT=8080
    mem_limit: 10m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adsb1.rule=Host(`adsb1.home.v9n.us`)"
      - "traefik.http.routers.adsb1.entrypoints=websecure"
      - "traefik.http.routers.adsb1.tls.certresolver=le"
      - "traefik.http.services.adsb1.loadbalancer.server.port=80"


networks:
  monitoring:
    driver: bridge
