#!/usr/bin/env bash

docker stop grafana
docker stop prometheus

docker run \
    --rm \
    --volumes-from grafana \
    -v ~/docker/backup/:/backup \
    ubuntu \
    bash -c "tar cfj /backup/grafana-`strdate`.tar.bz2 /var/lib/grafana"

#tar cvvfz backup/prometheus-`strdate`.tar.gz /var/lib/prometheus/master
#tar cvvf - /tmp | xz - - > foo
#tar cf - /var/lib/prometheus/master | pv | xz -T 1 - - > backup/prometheus-`strdate`.tar.xz
promback=backup/prometheus-`strdate`.tar
tar cf - /var/lib/prometheus/master | pv > $promback

docker start prometheus
docker start grafana

echo "Now compressing prometheus backup. This will take a long time (30m+)"
time xz $promback
