#!/usr/bin/env bash

set -u
set -e

datestamp=$(docker ps | grep hass | cut -d: -f2 | awk '{print $1}')_$(date -u +%Y%m%d-%H%M%S)

sudo id

docker stop hass
sudo tar cvvf hass-data-dir-$datestamp.tar hass-config
docker start hass
sudo bzip2 hass-data-dir-$datestamp.tar
