version: '2'

services:
  reverse-proxy:
    image: traefik:v2.1.4
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.file.directory=/conf"
      - "--providers.file.watch=true"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.web.address=:80"
      - "--certificatesResolvers.le.acme.email=trick@vanstaveren.us"
      - "--certificatesResolvers.le.acme.storage=/acme.json"
      #- "--certificatesResolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.le.acme.tlsChallenge=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--metrics.prometheus=true"
      - "--entryPoints.metrics.address=:7082"

    ports:
      - "443:443"
      - "80:80"
      - "8079:8080"
      - "7082:7082"
    volumes:
      - /root/docker/traefik/conf:/conf

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8077:80
    environment:
      WORDPRESS_DB_HOST: 172.16.12.2
      WORDPRESS_DB_USER: aircaretech_wp
      WORDPRESS_DB_PASSWORD: ncgdvUaSLc6eU3cmBmd5
      WORDPRESS_DB_NAME: aircaretech_wordpress
    volumes:
      - wordpress:/var/www/html

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.36.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    expose:
      - 8080
    ports:
      - "8005:8080"
    networks:
      - monitoring


volumes:
  wordpress:

networks:
  monitoring:
    driver: bridge
