http:
  routers:
    autorx:
      entryPoints:
        - "websecure"
      rule: "Host(`autorx.home.v9n.us`)"
      service: "autorx"
      tls:
        certResolver: le
      middlewares:
        - "github-auth@docker"

  services:
    autorx:
      loadBalancer:
        servers:
          - url: "http://green:5000"

