http:
  routers:
    chasemapper:
      entryPoints:
        - "websecure"
      rule: "Host(`chasemapper.home.v9n.us`)"
      service: "chasemapper"
      tls:
        certResolver: le
      middlewares:
        - "github-auth@docker"

  services:
    chasemapper:
      loadBalancer:
        servers:
          - url: "http://172.16.17.181:5001"

