http:
  routers:
    metra-schedule-1:
      entryPoints:
        - "websecure"
      rule: "Host(`metra-schedule-1.home.v9n.us`)"
      service: "metra-schedule-1"
      tls:
        certResolver: le

  services:
    metra-schedule-1:
      loadBalancer:
        servers:
          - url: "http://litecoin:8000"


