- id: turn on outdoor lights at sunset
  alias: turn on outdoor lights at sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: switch.turn_on
    data:
      entity_id:
      - switch.front_lights
- id: turn off outdoor lights at 10pm
  alias: turn off outdoor lights at 10pm
  trigger:
  - at: '22:00:00'
    platform: time
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id:
      - switch.front_lights
- id: tree on sunrise
  alias: turn on christmas tree near sunrise
  trigger:
  - event: sunrise
    platform: sun
    offset: -00:30:00
  condition: []
  action:
  - service: script.christmastreeon
- id: tree off sunrise
  alias: turn of christmas tree after sunrise
  trigger:
  - event: sunrise
    platform: sun
    offset: +02:00:00
  condition: []
  action:
  - service: script.christmastreeon
- id: tree on sunset
  alias: turn on christmas tree near sunset
  trigger:
  - event: sunset
    platform: sun
    offset: -00:30:00
  condition: []
  action:
  - service: script.christmastreeon
- id: tree off evening
  alias: turn off christmas tree late at night
  trigger:
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - service: script.christmastreeoff
- id: space heater on
  alias: space heater on
  trigger:
  - at: 06:00:00
    platform: time
  action:
  - service: script.spaceheatertoggle
- id: space heater off
  alias: space heater off
  trigger:
  - at: '20:30:00'
    platform: time
  action:
  - service: script.spaceheatertoggle
- id: '1610601254900'
  alias: Zigbee coord offline
  description: ''
  trigger:
  - device_id: d32453256e3baa07fd98fa84f9ebfe79
    domain: zha
    platform: device
    type: device_offline
    subtype: device_offline
  condition: []
  action:
  - device_id: d52a44b77c804db281802af791d8d3ef
    domain: mobile_app
    type: notify
    message: zigbee coord offline
    title: ''
  mode: single
