- id: turn on outdoor lights at sunset
  alias: turn on outdoor lights at sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: switch.turn_on
    data:
      entity_id:
      - switch.front_lights
- id: turn off outdoor lights at 10pm
  alias: turn off outdoor lights at night
  trigger:
  - at: '21:01:05'
    platform: time
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id:
      - switch.front_lights
  mode: single
- id: space heater on
  alias: space heater on morning
  trigger:
  - at: 07:00:00
    platform: time
  action:
  - service: script.spaceheatertoggle
  mode: single
- id: space heater off
  alias: space heater off morning
  trigger:
  - at: '10:00:00'
    platform: time
  action:
  - service: script.spaceheatertoggle
  mode: single
- id: '1610601254900'
  alias: Zigbee coord offline
  description: ''
  trigger:
  - device_id: d32453256e3baa07fd98fa84f9ebfe79
    domain: zha
    platform: device
    type: device_offline
    subtype: device_offline
  condition: []
  action:
  - device_id: d52a44b77c804db281802af791d8d3ef
    domain: mobile_app
    type: notify
    message: zigbee coord offline
    title: ''
  mode: single
- id: '1610686517820'
  alias: space heater on afternoon
  description: ''
  trigger:
  - platform: time
    at: '15:00:00'
  condition: []
  action:
  - service: script.spaceheatertoggle
    data: {}
  mode: single
- id: '1610686556109'
  alias: space heater off evening
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - service: script.spaceheatertoggle
    data: {}
  mode: single
- id: '1611114482176'
  alias: Tag A scan in office
  description: ''
  trigger:
  - platform: tag
    tag_id: e664296e-0823-42b9-8c84-afa287ccfd02
  condition: []
  action:
  - type: toggle
    device_id: 56d3bb99a887d39d5d9a37356de710e2
    entity_id: light.closet_ceiling_lamp
    domain: light
  - type: toggle
    device_id: 470a9ae157247c582dbd6e332ca4d777
    entity_id: light.the_home_depot_ecosmart_zbt_a19_cct_bulb_627e93fe_level_light_color_on_off
    domain: light
  mode: single
- id: '1611235873151'
  alias: CJ red christmas lights nfc tag
  description: ''
  trigger:
  - platform: tag
    tag_id: 53aac03f-ad3d-4c9b-b199-5e96d623cdab
  condition: []
  action:
  - type: toggle
    device_id: 68cbfff1d40d9adcf09446f0a3990b4a
    entity_id: switch.ewelink_sa_003_zigbee_1545981f_on_off
    domain: switch
  mode: single
- id: '1611545414210'
  alias: boiler scheduled on
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '0'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.boiler_east_1_25hp
  mode: single
- id: '1611545451637'
  alias: boiler scheduled off
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '20'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.boiler_east_1_25hp
  mode: single
- id: '1611635037918'
  alias: hack thermostat top
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.bedroom_temperature
    above: '67.5'
  condition: []
  action:
  - device_id: 7c2f464e4c06d2662de0f72a30aa4c7f
    domain: climate
    entity_id: climate.dining_room
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1611635088318'
  alias: hack thermostat bottom
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.bedroom_temperature
    below: '66.5'
  condition: []
  action:
  - device_id: 7c2f464e4c06d2662de0f72a30aa4c7f
    domain: climate
    entity_id: climate.dining_room
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1611837767885'
  alias: boiler overheat
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.boiler_hot_supply
    above: '190'
  condition: []
  action:
  - device_id: d52a44b77c804db281802af791d8d3ef
    domain: mobile_app
    type: notify
    message: boiler hot
    title: boiker overheating
  mode: single
- id: '1612029886139'
  alias: Cycle Boiler While Cool
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '3'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.boiler_east_1_25hp
  - delay: 0:15
  - service: switch.turn_off
    data: {}
    entity_id: switch.boiler_east_1_25hp
  mode: single
- id: '1612066319156'
  alias: boiler freeze warning
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.boiler_cool_return
    below: '38'
    for: 0:10
  condition: []
  action:
  - device_id: d52a44b77c804db281802af791d8d3ef
    domain: mobile_app
    type: notify
    message: freeze possible
    title: boiler freeze warning
  mode: single
- id: '1612420578646'
  alias: Office lights on evening
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.closet_ceiling_lamp
  - service: light.turn_on
    data: {}
    entity_id: light.the_home_depot_ecosmart_zbt_a19_cct_bulb_627e93fe_level_light_color_on_off
  mode: single
- id: '1612420745134'
  alias: office lights off at dinner
  description: ''
  trigger:
  - platform: time
    at: '17:30'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.closet_ceiling_lamp
  - service: light.turn_on
    data: {}
    entity_id: light.the_home_depot_ecosmart_zbt_a19_cct_bulb_627e93fe_level_light_color_on_off
  mode: single
- id: '1614231127176'
  alias: boiler cycle hourly
  description: ''
  trigger:
  - platform: time_pattern
    hours: '*'
    minutes: '50'
  condition: []
  action:
  - service: script.boiler_spike_run
    data: {}
  mode: single
- id: '1614353754547'
  alias: motion light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: 120
      motion_entity: binary_sensor.ewelink_ms01_motion_ias_zone
      light_target:
        entity_id: light.the_home_depot_ecosmart_zbt_a19_cct_bulb_level_light_color_on_off
- id: '1615695696754'
  alias: Cycle DR Radiator Sensor Power
  description: ''
  trigger:
  - platform: time_pattern
    hours: /1
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.ewelink_sa_003_zigbee_1545981f_on_off
  - delay: 0:45
  - service: switch.turn_off
    data: {}
    entity_id: switch.ewelink_sa_003_zigbee_1545981f_on_off
  mode: single
- id: '1616132884135'
  alias: boiler on http notify
  description: ''
  trigger:
  - platform: state
    entity_id: switch.boiler_east_1_25hp
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: shell_command.boiler_on
  mode: single
- id: '1616132903319'
  alias: boiler off http notify
  description: ''
  trigger:
  - platform: state
    entity_id: switch.boiler_east_1_25hp
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: shell_command.boiler_off
  mode: single
- id: '1616726294569'
  alias: miner off!
  description: ''
  trigger:
  - platform: time
    at: '23:59:00'
  condition: []
  action:
  - service: script.christmastreeoff
  mode: single
- id: '1617891510203'
  alias: Cycle HVAC temperature sensor box
  description: ''
  trigger:
  - platform: time_pattern
    hours: '4'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.hvac_temp_box
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: switch.turn_on
    target:
      entity_id: switch.hvac_temp_box
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: switch.turn_on
    target:
      entity_id: switch.hvac_temp_box
  mode: single
- id: '1618778612817'
  alias: motion basement big lights
  description: ''
  use_blueprint:
    path: freakshock88/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.ewelink_ms01_motion_ias_zone
      no_motion_wait: '2'
      target_entity: switch.basement_big_lights
- id: '1619149080175'
  alias: turn off outdoor lights at night 2
  description: Just in case.
  trigger:
  - at: '22:00:00'
    platform: time
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id:
      - switch.front_lights
  mode: single
- id: '1620855756768'
  alias: Switch test
  description: ''
  use_blueprint:
    path: garykrige/zha-sonoff-zigbee-switch.yaml
    input:
      sonoff_button: 8ae72a8034c3c3a090b27b9d00d1ade0
      toggle_action:
      - service: notify.mobile_app_trickyplus
        data:
          title: single press button
          message: Test
