
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
frontend:
sun:
timer:
updater:
person:
logbook:
config:
mobile_app:
system_health:
prometheus:
history:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mochad:
  host: mash.home.vanstaveren.us

switch:
  - platform: mochad
    devices:
      - address: c3
        name: HVAC temp box
        comm_type: rf
      - address: c7
        name: Office temp box
        comm_type: rf
      - address: c8
        name: Garage Lights
        comm_type: rf
      - address: c10
        name: Front Lights
        comm_type: rf
  - platform: remote_rpi_gpio
    host: jimmy.home.vanstaveren.us
    ports:
      17: Space Heater Relay
  - platform: remote_rpi_gpio
    host: 172.16.17.28
    invert_logic: true
    ports:
      17: Boiler West 1/12hp
      27: Boiler East 1/25hp
ifttt:
  key: bWDYaMaVYJf9_2PvfBqsnl

nest:
  client_id: 320399857508-vcdobu2sn65h4a05usktf99okl6n3s1i.apps.googleusercontent.com
  client_secret: !secret nest_client_secret
  project_id: f0d76122-8194-4fe4-998e-434ca4a98ecc
  subscriber_id: projects/hass1-302004/subscriptions/hass1

climate:
  - platform: generic_thermostat
    name: Boiler East
    heater: switch.boiler_east_1_25hp
    target_sensor: sensor.pws_dr_temperature
    target_temp: 69
    min_cycle_duration:
      minutes: 1

solaredge:
  api_key: R3QWABJRVG0V88WGDSQDI3X997W9IU8Q
  site_id: 1735273
