
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
frontend:
sun:
timer:
updater:
person:
logbook:
config:
mobile_app:
system_health:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mochad:
  host: mash.home.vanstaveren.us

switch:
  - platform: mochad
    devices:
      - address: c3
        name: HVAC temp box
        comm_type: rf
      - address: c7
        name: Office temp box
        comm_type: rf
      - address: c8
        name: Garage Lights
        comm_type: rf
#      - address: c9
#        name: Tree
#        comm_type: rf
      - address: c10
        name: Front Lights
        comm_type: rf
  - platform: remote_rpi_gpio
    host: 172.16.17.18
    ports:
      17: Space Heater Relay
ifttt:
  key: bWDYaMaVYJf9_2PvfBqsnl
