
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
frontend:
sun:
timer:
updater:
person:
logbook:
config:
mobile_app:
system_health:
prometheus:
history:
my:
energy:
input_number:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mochad:
  host: mash.home.vanstaveren.us

switch:
  - platform: mochad
    devices:
      - address: c1
        name: RF box outlet
        comm_type: rf
      - address: c2
        name: Basement big lights
        comm_type: rf
      - address: c3
        name: HVAC temp box
        comm_type: rf
      - address: c5
        name: Dehumidifier
        comm_type: rf
      - address: c8
        name: Garage Lights
        comm_type: rf
  - platform: remote_rpi_gpio
    host: jimmy.home.vanstaveren.us
    invert_logic: true
    ports:
      17: Space Heater Relay
  - platform: remote_rpi_gpio
    host: thermostatpi.home.vanstaveren.us
    invert_logic: true
    ports:
      17: Boiler West New Grundfos
      27: Boiler East 1/25hp

climate:
  - platform: generic_thermostat
    name: Boiler East
    heater: switch.boiler_east_1_25hp
    target_sensor: sensor.e_temperature
    target_temp: 69
    min_cycle_duration:
      minutes: 1
    precision: 0.1
  - platform: generic_thermostat
    name: Boiler West
    heater: switch.boiler_west_new_grundfos
    target_sensor: sensor.esp46a646_temperature
    target_temp: 69.5
    min_cycle_duration:
      minutes: 1
    precision: 0.1
#  - platform: generic_thermostat
#    ac_mode: true
#    name: BR Fan
#    heater: switch.ewelink_sa_003_zigbee_1545981f_on_off
#    target_sensor: sensor.bedroom_temperature_2
#    target_temp: 74
#    min_cycle_duration:
#      minutes: 1

shell_command:
  boiler_on: !secret boiler_on_notify_shell_command
  boiler_off: !secret boiler_off_notify_shell_command

sensor:
  - platform: comed_hourly_pricing
    monitored_feeds:
      - type: five_minute
      - type: current_hour_average
  - platform: template
    sensors:
      bedrooms_temp_difference:
        friendly_name: "Difference between bedrooms"
        unit_of_measurement: "F"
        value_template: '{{ float(states("sensor.bedroom_temperature_2")) - float(states("sensor.dining_room_2_temperature")) }}'
      combined_solar_forecast_today:
        friendly_name: "Combined Solar.Forecast Today"
        unit_of_measurement: "kWh"
        value_template: '{{ float(states("sensor.forecast_solar_south_energy_production_today")) + float(states("sensor.forecast_solar_west_energy_production_today")) + float(states("sensor.forecast_solar_east_energy_production_today")) }}'
      combined_solar_forecast_tomorrow:
        friendly_name: "Combined Solar.Forecast Tomorrow"
        unit_of_measurement: "kWh"
        value_template: '{{ float(states("sensor.forecast_solar_south_energy_production_tomorrow")) + float(states("sensor.forecast_solar_west_energy_production_tomorrow")) + float(states("sensor.forecast_solar_east_energy_production_tomorrow")) }}'

template:
  - sensor:
      - name: "Grid Consumption Today Derived"
        unit_of_measurement: "Wh"
        state: >
          {{ float(states("sensor.total_daily_energy")) - float(states("sensor.solaredge_energy_today")) }}
        device_class: energy
        state_class: total
