- id: '1622245998610'
  name: bedtime dim
  entities:
    light.the_home_depot_ecosmart_zbt_a19_cct_bulb_a2242efe_level_light_color_on_off:
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 5
      color_temp: 370
      off_brightness:
      friendly_name: The Home Depot Ecosmart-ZBT-A19-CCT-Bulb a2242efe level, light_color,
        on_off
      supported_features: 43
      state: 'on'
- id: '1622246040229'
  name: bedtime reading
  entities:
    light.the_home_depot_ecosmart_zbt_a19_cct_bulb_a2242efe_level_light_color_on_off:
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 51
      color_temp: 370
      hs_color:
      - 28.391
      - 65.659
      rgb_color:
      - 255
      - 166
      - 87
      xy_color:
      - 0.526
      - 0.387
      off_brightness:
      friendly_name: cj zamppp
      supported_features: 43
      state: 'on'
- id: '1622246150071'
  name: lights out
  entities:
    light.the_home_depot_ecosmart_zbt_a19_cct_bulb_a2242efe_level_light_color_on_off:
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - color_temp
      off_brightness:
      friendly_name: The Home Depot Ecosmart-ZBT-A19-CCT-Bulb a2242efe level, light_color,
        on_off
      supported_features: 43
      state: 'off'
