
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
#frontend:
#sun:
#timer:
#updater:
#person:
#logbook:
#config:
#mobile_app:
#system_health:
prometheus:
#history:
#my:
#energy:
#input_number:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.17.0/24
    - 172.21.0.0/16
    - 172.17.0.0/16
    - 172.18.0.0/16
    - 172.19.0.0/16
    - 127.0.0.0/16

homeassistant:
  allowlist_external_dirs:
    - "/config/tmp"

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


climate:
#  - platform: generic_thermostat
#    ac_mode: true
#    name: Kids BR Fan
#    heater: switch.s31_h_relay
#    # ecobee remote sensor
#    target_sensor: sensor.dining_room_2_temperature
#    target_temp: 74
#    min_cycle_duration:
#      minutes: 1
#  - platform: generic_thermostat
#    name: BR Fan
#    ac_mode: true
#    heater: switch.s31_m_relay
    # target_sensor: sensor.bedroom_temperature_2 # noisy
#    target_sensor: sensor.f_temperature # bat died Apr 24, this is better...
    #target_sensor: sensor.bedroom_temperature_2
#    target_temp: 74
#    min_cycle_duration:
#      minutes: 1
#    precision: 0.1
#  - platform: generic_thermostat
#    name: CJ Fan
#    ac_mode: true
#    heater: switch.jeeoa_socket
#    target_sensor: sensor.dining_room_2_temperature
#    target_temp: 74
#    min_cycle_duration:
#      minutes: 1
#    precision: 0.1

shell_command:
  boiler_on: !secret boiler_on_notify_shell_command
  boiler_off: !secret boiler_off_notify_shell_command
  octopi_off: !secret octopi_shutdown_command

sensor:
  - platform: history_stats
    name: Boiler East ON Today
    entity_id: switch.east
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Boiler West ON Today
    entity_id: switch.west
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Boiler East ON Today Ratio
    entity_id: switch.east
    state: "on"
    type: ratio
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Boiler West ON Today Ratio
    entity_id: switch.west
    state: "on"
    type: ratio
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Forced Air ON Today Time
    entity_id: sensor.forced_air_action
    state: "heating"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Forced Air ON Today Ratio
    entity_id: sensor.forced_air_action
    state: "heating"
    type: ratio
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Forced Air Cooling ON Today Ratio
    entity_id: sensor.forced_air_action
    state: "cooling"
    type: ratio
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Forced Air Cooling ON Today Time
    entity_id: sensor.forced_air_action
    state: "cooling"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Bathroom Floor Heating Daily
    entity_id: sensor.bathroom_floor_heating_action
    state: "heating"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Boiler East ON rolling ratio 24h
    entity_id: switch.east
    state: "on"
    type: ratio
    end: "{{ now() }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Boiler East ON rolling ratio 6h
    entity_id: switch.east
    state: "on"
    type: ratio
    end: "{{ now() }}"
    duration:
      hours: 6
  - platform: comed_hourly_pricing
    monitored_feeds:
      - type: five_minute
      - type: current_hour_average

  - platform: derivative
    name: "solaredge2mqtt Module 127F8879-92 Power (Derivative)"
    source: sensor.solaredge2mqtt_module_127f8879_92_energy
    unit_time: h
  - platform: derivative
    name: "solaredge2mqtt Module 127F7E57-66 Power (Derivative)"
    source: sensor.solaredge2mqtt_module_127f7e57_66_energy
    unit_time: h
  - platform: derivative
    name: "solaredge2mqtt Module 127DB2F1-32 Power (Derivative)"
    source: sensor.solaredge2mqtt_module_127db2f1_32_energy
    unit_time: h
  - platform: derivative
    name: "solaredge2mqtt Module 127F55D8-BE Power (Derivative)"
    source: sensor.solaredge2mqtt_module_127f55d8_be_energy
    unit_time: h
  - platform: derivative
    name: "solaredge2mqtt Module 127F829C-AF Power (Derivative)"
    source: sensor.solaredge2mqtt_module_127f829c_af_energy
    unit_time: h
  - platform: derivative
    name: "solaredge2mqtt Module 127F4BC6-A2 Power (Derivative)"
    source: sensor.solaredge2mqtt_module_127f4bc6_a2_energy
    unit_time: h
  - platform: derivative
    name: "solaredge2mqtt Module 127FC84B-A4 Power (Derivative)"
    source: sensor.solaredge2mqtt_module_127fc84b_a4_energy
    unit_time: h
  - platform: derivative
    name: "solaredge2mqtt Module 12709E7E-9E Power (Derivative)"
    source: sensor.solaredge2mqtt_module_12709e7e_9e_energy
    unit_time: h
  - platform: derivative
    name: "solaredge2mqtt Module 127DB1A0-E0 Power (Derivative)"
    source: sensor.solaredge2mqtt_module_127db1a0_e0_energy
    unit_time: h
  - platform: derivative
    name: "solaredge2mqtt Module 127F827E-91 Power (Derivative)"
    source: sensor.solaredge2mqtt_module_127f827e_91_energy
    unit_time: h
  - platform: derivative
    name: "solaredge2mqtt Module 127E58F6-DE Power (Derivative)"
    source: sensor.solaredge2mqtt_module_127e58f6_de_energy
    unit_time: h
  - platform: derivative
    name: "solaredge2mqtt Module 127FD1F6-58 Power (Derivative)"
    source: sensor.solaredge2mqtt_module_127fd1f6_58_energy
    unit_time: h
  - platform: derivative
    name: "solaredge2mqtt Module 127E588B-73 Power (Derivative)"
    source: sensor.solaredge2mqtt_module_127e588b_73_energy
    unit_time: h
  - platform: derivative
    name: "solaredge2mqtt Module 127F80CF-E0 Power (Derivative)"
    source: sensor.solaredge2mqtt_module_127f80cf_e0_energy
    unit_time: h



template:
  - sensor:
      - name: "Claude Session Reset"
        device_class: timestamp
        state: "{{ states('sensor.claude_code_session_reset_time') | as_datetime | as_local }}"
      - name: "Claude Week Reset"
        device_class: timestamp
        state: "{{ states('sensor.claude_code_week_reset_time') | as_datetime | as_local }}"
      - name: "Grid Consumption Today Derived"
        unit_of_measurement: "Wh"
        state: >
          {{ float(states("sensor.total_daily_energy")) - float(states("sensor.solaredge_energy_today")) }}
        device_class: energy
        state_class: total
      - name: "Forced Air Action"
        state: "{{ state_attr('climate.dining_room_2', 'hvac_action') }}"
      - name: "Bathroom floor heating action"
        state: "{{ state_attr('climate.ditra_heat_e_rs1', 'hvac_action') }}"
      - name: "Bathroom floor heating energy daily"
        unit_of_measurement: "kWh"
        state: "{{ (states('sensor.bathroom_floor_heating_daily') | float * 0.475) | round(2) }}"
        device_class: "energy"
      - name: "Difference between bedrooms"
        unit_of_measurement: "F"
        state: "{{ float(states('sensor.bedroom_temperature_2')) - float(states('sensor.dining_room_2_temperature')) }}"
      - name: "Combined Solar.Forecast Today"
        unit_of_measurement: "kWh"
        state: "{{ float(states('sensor.forecast_solar_south_energy_production_today')) + float(states('sensor.forecast_solar_west_energy_production_today')) + float(states('sensor.forecast_solar_east_energy_production_today')) }}"
      - name: "Combined Solar.Forecast Tomorrow"
        unit_of_measurement: "kWh"
        state: "{{ float(states('sensor.forecast_solar_south_energy_production_tomorrow')) + float(states('sensor.forecast_solar_west_energy_production_tomorrow')) + float(states('sensor.forecast_solar_east_energy_production_tomorrow')) }}"
  - trigger:
      - platform: event
        event_type: sonde_alert
        event_data:
          user: person.matt
    sensor:
      - name: "Sonde Alert Matt"
        state: "{{ trigger.event.data.sonde_id }}"
        attributes:
          sonde_id: "{{ trigger.event.data.sonde_id }}"
          distance_km: "{{ trigger.event.data.distance_km }}"
          sonde_lat: "{{ trigger.event.data.sonde_lat }}"
          sonde_lon: "{{ trigger.event.data.sonde_lon }}"
          sonde_alt: "{{ trigger.event.data.sonde_alt }}"
          sonde_url: "{{ trigger.event.data.sonde_url }}"
          landed_ago: "{{ trigger.event.data.landed_ago }}"
          message: "{{ trigger.event.data.message }}"
          last_updated: "{{ now().isoformat() }}"
  - trigger:
      - platform: event
        event_type: sonde_alert
        event_data:
          user: person.patrick_van_staveren
    sensor:
      - name: "Sonde Alert Trick"
        state: "{{ trigger.event.data.sonde_id }}"
        attributes:
          sonde_id: "{{ trigger.event.data.sonde_id }}"
          distance_km: "{{ trigger.event.data.distance_km }}"
          sonde_lat: "{{ trigger.event.data.sonde_lat }}"
          sonde_lon: "{{ trigger.event.data.sonde_lon }}"
          sonde_alt: "{{ trigger.event.data.sonde_alt }}"
          sonde_url: "{{ trigger.event.data.sonde_url }}"
          landed_ago: "{{ trigger.event.data.landed_ago }}"
          message: "{{ trigger.event.data.message }}"
          last_updated: "{{ now().isoformat() }}"

intent_script:
  GetTime:
    speech:
      text: The time is {{ now().strftime('%-I:%M') }}

mqtt:
  sensor:
    - name: "OctoPrint Z Height"
      state_topic: "octoPrint/event/ZChange"
      unit_of_measurement: "mm"
      value_template: "{{ value_json.new }}"
      icon: "mdi:axis-z-arrow"
    - name: "solaredge2mqtt Solaredge Total Energy"
      state_topic: "solaredge/modbus/inverter"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energytotal }}"
      json_attributes_topic: "solaredge/modbus/inverter"
      expire_after: 60
    - name: "solaredge2mqtt Solaredge Power Actual"
      state_topic: "solaredge/modbus/inverter"
      availability:
        - topic: "solaredge/status"
      value_template: "{{ value_json.ac.power.actual}}"
      expire_after: 60
    - name: "solaredge2mqtt Solaredge Power Reactive"
      state_topic: "solaredge/modbus/inverter"
      availability:
        - topic: "solaredge/status"
      value_template: "{{ value_json.ac.power.reactive}}"
      expire_after: 60
    - name: "solaredge2mqtt Solaredge Power Apparent"
      state_topic: "solaredge/modbus/inverter"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.ac.power.apparent }}"
      expire_after: 60
    - name: "solaredge2mqtt Solaredge Power Factor"
      state_topic: "solaredge/modbus/inverter"
      availability:
        - topic: "solaredge/status"
      value_template: "{{ value_json.ac.power.factor }}"
      expire_after: 60
    - name: "solaredge2mqtt Solaredge Power Frequency"
      state_topic: "solaredge/modbus/inverter"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Hz"
      value_template: "{{ value_json.ac.frequency }}"
      expire_after: 60
    - name: "solaredge2mqtt Solaredge Status"
      state_topic: "solaredge/modbus/inverter"
      availability:
        - topic: "solaredge/status"
      value_template: "{{ value_json.status }}"
      expire_after: 60
    - name: "solaredge2mqtt Powerflow"
      state_topic: "solaredge/powerflow"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.pv_production}}"
      json_attributes_topic: "solaredge/powerflow"
      expire_after: 60
    - name: "solaredge2mqtt AC Power"
      state_topic: "solaredge/modbus/inverter"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "W"
      value_template: "{{ value_json.ac.power.actual}}"
      json_attributes_topic: "solaredge/modbus/inverter"
      expire_after: 60

      # panels:
    - name: "solaredge2mqtt Module 127F8879-92 Energy"
      state_topic: "solaredge/monitoring/module/127F8879-92"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/127F8879-92"
      expire_after: 1200
    - name: "solaredge2mqtt Module 127F7E57-66 Energy"
      state_topic: "solaredge/monitoring/module/127F7E57-66"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/127F7E57-66"
      expire_after: 1200
    - name: "solaredge2mqtt Module 127DB2F1-32 Energy"
      state_topic: "solaredge/monitoring/module/127DB2F1-32"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/127DB2F1-32"
      expire_after: 1200
    - name: "solaredge2mqtt Module 127F55D8-BE Energy"
      state_topic: "solaredge/monitoring/module/127F55D8-BE"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/127F55D8-BE"
      expire_after: 1200
    - name: "solaredge2mqtt Module 127F829C-AF Energy"
      state_topic: "solaredge/monitoring/module/127F829C-AF"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/127F829C-AF"
      expire_after: 1200
    - name: "solaredge2mqtt Module 127F4BC6-A2 Energy"
      state_topic: "solaredge/monitoring/module/127F4BC6-A2"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/127F4BC6-A2"
      expire_after: 1200
    - name: "solaredge2mqtt Module 127FC84B-A4 Energy"
      state_topic: "solaredge/monitoring/module/127FC84B-A4"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/127FC84B-A4"
      expire_after: 1200
    - name: "solaredge2mqtt Module 12709E7E-9E Energy"
      state_topic: "solaredge/monitoring/module/12709E7E-9E"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/12709E7E-9E"
      expire_after: 1200
    - name: "solaredge2mqtt Module 127DB1A0-E0 Energy"
      state_topic: "solaredge/monitoring/module/127DB1A0-E0"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/127DB1A0-E0"
      expire_after: 1200
    - name: "solaredge2mqtt Module 127F827E-91 Energy"
      state_topic: "solaredge/monitoring/module/127F827E-91"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/127F827E-91"
      expire_after: 1200
    - name: "solaredge2mqtt Module 127E58F6-DE Energy"
      state_topic: "solaredge/monitoring/module/127E58F6-DE"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/127E58F6-DE"
      expire_after: 1200
    - name: "solaredge2mqtt Module 127FD1F6-58 Energy"
      state_topic: "solaredge/monitoring/module/127FD1F6-58"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/127FD1F6-58"
      expire_after: 1200
    - name: "solaredge2mqtt Module 127E588B-73 Energy"
      state_topic: "solaredge/monitoring/module/127E588B-73"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/127E588B-73"
      expire_after: 1200
    - name: "solaredge2mqtt Module 127F80CF-E0 Energy"
      state_topic: "solaredge/monitoring/module/127F80CF-E0"
      availability:
        - topic: "solaredge/status"
      unit_of_measurement: "Wh"
      value_template: "{{ value_json.energy }}"
      json_attributes_topic: "solaredge/monitoring/module/127F80CF-E0"
      expire_after: 1200

rest_command:
  radiopi_pan_left:
    url: "http://radiopi:8070/pan/left"
    method: "get"
  radiopi_pan_right:
    url: "http://radiopi:8070/pan/right"
    method: "get"
  radiopi_zoom_in:
    url: "http://radiopi:8070/zoom/in"
    method: "get"
  radiopi_zoom_out:
    url: "http://radiopi:8070/zoom/out"
    method: "get"
  radiopi_tilt_up:
    url: "http://radiopi:8070/tilt/up"
    method: "get"
  radiopi_tilt_down:
    url: "http://radiopi:8070/tilt/down"
    method: "get"
  radiopi_reset:
    url: "http://radiopi:8070/reset"
    method: "get"
  radiopi_focus_infinity:
    url: "http://radiopi:8070/focus/infinity"
    method: "get"
  octoprint_z100:
    url: "http://octopi/api/printer/command"
    method: "post"
    headers:
      X-Api-Key: !secret octoprint_api_key
      Content-Type: "application/json"
    payload: '{"commands": ["G0 Z100"]}'
  octoprint_hotend_warm:
    url: "http://octopi/api/printer/command"
    method: "post"
    headers:
      X-Api-Key: !secret octoprint_api_key
      Content-Type: "application/json"
    payload: '{"commands": ["M104 S190"]}'
  octoprint_hotend_off:
    url: "http://octopi/api/printer/command"
    method: "post"
    headers:
      X-Api-Key: !secret octoprint_api_key
      Content-Type: "application/json"
    payload: '{"commands": ["M104 S0"]}'
